# Generated by Django 3.0.1 on 2020-11-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoTestingApp', '0003_auto_20201123_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(default='fa-facebook', max_length=50, verbose_name='Font Awesome Icon'),
            preserve_default=False,
        ),
    ]
