# Generated by Django 3.0.1 on 2020-11-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoTestingApp', '0004_sociallink_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_center_name', models.CharField(max_length=50, verbose_name='centro de estudios')),
                ('course_name', models.CharField(max_length=50, verbose_name='curso')),
                ('average_grades', models.FloatField(verbose_name='promedio')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(verbose_name='fecha de fin')),
            ],
        ),
    ]
