# Generated by Django 3.0.1 on 2020-11-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoTestingApp', '0007_skill_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_icon',
            field=models.CharField(max_length=50, verbose_name='Icono Font Awesome'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='workflow_name',
            field=models.CharField(max_length=50, verbose_name='Flujo de trabajo'),
        ),
    ]
